name: My First Workflow

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]

  schedule:
    - cron: "1,31 8-18 * * 1-5"

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  First-Job:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - run: |
          echo "This job was triggered by ${{ github.event_name }}"
          echo "Branch name is ${{ github.ref }} and repository is ${{ github.repository }}."
          echo "Triggered by: ${{ github.actor }} using ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY

      - uses: actions/checkout@v4

      - name: List repo files
        run: |
          echo "${{ github.repository }} contains:"
          echo "::group::Directory Structure"
          tree . -L 5
          echo "::endgroup::"
          echo "::group::Github object"
          echo '${{ toJson(github) }}'
          echo "::endgroup::"

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: First-Job
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: First-Job
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Load testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'Production'
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
